name: Main
on:
  push:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test:ci
      - name: Test e2e
        run: npm run test:e2e
