name: Main
on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test:ci
  cypress-run:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - uses: actions/checkout@v4
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_XERRADA_PIA_TESTING }}"
          projectId: xerrada-pia-testing
